package entidades;
// Generated 24/06/2019 11:12:26 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ClienteHasMascota generated by hbm2java
 */
public class ClienteHasMascota  implements java.io.Serializable {


     private ClienteHasMascotaId id;
     private Cliente cliente;
     private Mascota mascota;
     private Character estado;
     private Set atencions = new HashSet(0);

    public ClienteHasMascota() {
    }

	
    public ClienteHasMascota(ClienteHasMascotaId id, Cliente cliente, Mascota mascota) {
        this.id = id;
        this.cliente = cliente;
        this.mascota = mascota;
    }
    public ClienteHasMascota(ClienteHasMascotaId id, Cliente cliente, Mascota mascota, Character estado, Set atencions) {
       this.id = id;
       this.cliente = cliente;
       this.mascota = mascota;
       this.estado = estado;
       this.atencions = atencions;
    }
   
    public ClienteHasMascotaId getId() {
        return this.id;
    }
    
    public void setId(ClienteHasMascotaId id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Mascota getMascota() {
        return this.mascota;
    }
    
    public void setMascota(Mascota mascota) {
        this.mascota = mascota;
    }
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }
    public Set getAtencions() {
        return this.atencions;
    }
    
    public void setAtencions(Set atencions) {
        this.atencions = atencions;
    }




}


