package entidades;
// Generated 13/07/2019 10:24:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Mascota generated by hbm2java
 */
public class Mascota  implements java.io.Serializable {


     private Integer idMascota;
     private String nameCliente;
     private String nameMascota;
     private String raza;
     private Set clienteHasMascotas = new HashSet(0);

    public Mascota() {
    }

	
    public Mascota(String nameCliente, String nameMascota, String raza) {
        this.nameCliente = nameCliente;
        this.nameMascota = nameMascota;
        this.raza = raza;
    }
    public Mascota(String nameCliente, String nameMascota, String raza, Set clienteHasMascotas) {
       this.nameCliente = nameCliente;
       this.nameMascota = nameMascota;
       this.raza = raza;
       this.clienteHasMascotas = clienteHasMascotas;
    }
   
    public Integer getIdMascota() {
        return this.idMascota;
    }
    
    public void setIdMascota(Integer idMascota) {
        this.idMascota = idMascota;
    }
    public String getNameCliente() {
        return this.nameCliente;
    }
    
    public void setNameCliente(String nameCliente) {
        this.nameCliente = nameCliente;
    }
    public String getNameMascota() {
        return this.nameMascota;
    }
    
    public void setNameMascota(String nameMascota) {
        this.nameMascota = nameMascota;
    }
    public String getRaza() {
        return this.raza;
    }
    
    public void setRaza(String raza) {
        this.raza = raza;
    }
    public Set getClienteHasMascotas() {
        return this.clienteHasMascotas;
    }
    
    public void setClienteHasMascotas(Set clienteHasMascotas) {
        this.clienteHasMascotas = clienteHasMascotas;
    }




}


