package entidades;
// Generated 13/07/2019 10:24:01 PM by Hibernate Tools 4.3.1



/**
 * Sexo generated by hbm2java
 */
public class Sexo  implements java.io.Serializable {


     private Integer idSexo;
     private String descripcion;

    public Sexo() {
    }

    public Sexo(String descripcion) {
       this.descripcion = descripcion;
    }
   
    public Integer getIdSexo() {
        return this.idSexo;
    }
    
    public void setIdSexo(Integer idSexo) {
        this.idSexo = idSexo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


