package entidades;
// Generated 19/07/2019 12:56:32 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipoatencion generated by hbm2java
 */
public class Tipoatencion  implements java.io.Serializable {


     private Integer idTipoAtencion;
     private String descripcion;
     private Set atencions = new HashSet(0);

    public Tipoatencion() {
    }

    public Tipoatencion(String descripcion, Set atencions) {
       this.descripcion = descripcion;
       this.atencions = atencions;
    }
   
    public Integer getIdTipoAtencion() {
        return this.idTipoAtencion;
    }
    
    public void setIdTipoAtencion(Integer idTipoAtencion) {
        this.idTipoAtencion = idTipoAtencion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getAtencions() {
        return this.atencions;
    }
    
    public void setAtencions(Set atencions) {
        this.atencions = atencions;
    }




}


